const fs=require('fs'),vm=require('vm'),assert=require('assert');
const path=require('path');const src=fs.readFileSync(process.argv[2]||path.join(__dirname,'../Legioes_do_Eclipse_v2_5_MATERIAIS_ANIMADOS.html'),'utf8');
const base=src.match(/<script>([\s\S]*?)<\/script>/)[1];
const injection=`window.test={resetArena,configureFighter,makeUnit,circleResolve,updateMover,updateArena,updateBoard,finishDuel,afterMove,showTraining,setMode,close,keys,boardClick,startBoardMove,getUnits:()=>units,getTerrain:()=>terrain,getWinner:()=>winner,getTime:()=>turnTime,setTime:v=>turnTime=v};`;
function boot(){const els=new Map();function el(id){if(!els.has(id))els.set(id,{hidden:false,value:'',dataset:{},style:{},classList:{toggle(){}},addEventListener(t,f){this[t]=f},getContext:()=>({}),getBoundingClientRect:()=>({left:0,top:0,width:1280,height:720})});return els.get(id)}const tabs=['board','arena'].map(mode=>{const e=el('tab'+mode);e.dataset.mode=mode;return e});const win={addEventListener(){}};const sandbox={window:win,document:{getElementById:el,querySelector:el,querySelectorAll:q=>q==='.tab'?tabs:[]},Image:class{constructor(){this.complete=true;this.naturalWidth=160}},requestAnimationFrame(){},console,performance:{now:()=>0}};vm.createContext(sandbox);vm.runInContext(base.replace(/\}\)\(\);\s*$/,injection+'})();'),sandbox);return {d:win.__dl,t:win.test,el,tabs}}
const results=[];function test(name,fn){try{fn(boot());results.push({name,status:'PASS'})}catch(e){results.push({name,status:'FAIL',detail:e.message})}}
function duel(b){b.d.start();b.d.encounter();b.el('enterDuel').onclick();return b.d.getArena()}
function training(b,id='templar'){b.d.start();b.t.showTraining();b.el('trainP').value=id;b.el('trainE').value='orc';b.el('startTrain').onclick();return b.d.getArena()}
test('Inicialização: 8 unidades e atributos finitos',b=>{b.d.start();assert.equal(b.d.getState().units.length,8);for(const u of b.d.getState().units)assert(Number.isFinite(u.hp)&&u.hp>0&&u.mp>0)});
test('Turnos: alternância e incremento de rodada',b=>{b.d.start();b.d.endTurn();assert.equal(b.d.getState().turn,1);b.d.endTurn();assert.equal(b.d.getState().turn,0);assert.equal(b.d.getState().round,2)});
test('Reposição de movimento ao iniciar turno',b=>{b.d.start();const u=b.t.getUnits()[0];u.mp=0;b.d.endTurn();b.d.endTurn();assert.equal(u.mp,u.baseMp)});
test('Cronômetro expira e troca turno',b=>{b.d.start();b.t.setTime(.001);b.t.updateBoard(1/120);assert.equal(b.d.getState().turn,1)});
test('Modal pausa cronômetro e bloqueia encerrar turno',b=>{b.d.start();b.d.encounter();const n=b.t.getTime();b.t.updateBoard(1);b.d.endTurn();assert.equal(b.t.getTime(),n);assert.equal(b.d.getState().turn,0)});
test('Movimento: custo, destino e bloqueio de turno durante animação',b=>{b.d.start();const u=b.t.getUnits()[0],r=b.d.reachable(u).find(x=>x.cost>0),route=b.d.pathfind(u,r),mp=u.mp;b.t.startBoardMove(u,route);b.d.endTurn();assert.equal(b.d.getState().turn,0);assert.equal(u.mp,mp-route.cost);for(let i=0;i<500;i++)b.t.updateBoard(1/120);assert.equal(u.c,r.c);assert.equal(u.r,r.r);assert(!u.moving)});
test('Rotas: custo dentro do orçamento e passos ortogonais',b=>{b.d.start();for(const u of b.t.getUnits())for(const r of b.d.reachable(u)){const p=b.d.pathfind(u,r);assert(p.cost<=u.mp);for(let i=1;i<p.path.length;i++)assert.equal(Math.abs(p.path[i].c-p.path[i-1].c)+Math.abs(p.path[i].r-p.path[i-1].r),1)}});
test('Entrada de duelo preserva vida da unidade',b=>{b.d.start();b.t.getUnits()[0].hp=43;b.d.encounter();b.el('enterDuel').onclick();assert.equal(b.d.getArena().player.hp,43)});
test('Vitória remove adversário e preserva vida do vencedor',b=>{const a=duel(b);a.player.hp=42;a.enemy.hp=0;b.t.finishDuel();b.el('returnDuel').onclick();assert.equal(b.d.getState().units.length,7);assert.equal(b.d.getState().units.find(u=>u.team===0).hp,42);assert.equal(b.d.getState().mode,'board');assert(!b.d.getState().duel)});
test('Derrota remove criatura do jogador',b=>{const a=duel(b);a.player.hp=0;b.t.finishDuel();b.el('returnDuel').onclick();assert.equal(b.d.getState().units.filter(u=>u.team===0).length,3)});
test('Empate conserva unidades e posições',b=>{const a=duel(b),before=b.d.getState().units.map(u=>[u.id,u.c,u.r]);a.player.hp=a.player.max/2;a.enemy.hp=a.enemy.max/2;b.t.finishDuel();b.el('returnDuel').onclick();assert.deepEqual(b.d.getState().units.map(u=>[u.id,u.c,u.r]),before)});
test('Duelo encerra aos 120 segundos',b=>{const a=duel(b);a.time=119.999;b.t.updateArena(1/120);assert(a.over)});
test('Treino preserva estado do tabuleiro',b=>{b.d.start();const before=JSON.stringify(b.d.getState().units);training(b);b.d.finish();b.el('returnDuel').onclick();assert.equal(JSON.stringify(b.d.getState().units),before)});
test('Captura do orbe encerra partida',b=>{b.d.start();const u=b.t.getUnits()[0];u.c=13;u.r=3;b.t.afterMove(u);assert.equal(b.t.getWinner(),0)});
test('Colisão desloca corpo sobreposto fora do centro',b=>{const a={x:405,y:260,r:24,vx:-1,vy:0};b.t.circleResolve(a,400,260,48);assert(Math.hypot(a.x-400,a.y-260)>=72-1e-8)});
test('Colisão resolve corpo exatamente no centro do obstáculo',b=>{const a={x:400,y:260,r:24,vx:0,vy:0};b.t.circleResolve(a,400,260,48);assert(Math.hypot(a.x-400,a.y-260)>=72-1e-8,'Corpo permaneceu no centro do obstáculo')});
test('Entrada pela aba Arena permite atualizar combate',b=>{b.d.start();b.tabs[1].click();b.t.updateArena(1/120);for(const e of [b.d.getArena().player,b.d.getArena().enemy])assert(Number.isFinite(e.x)&&Number.isFinite(e.speed))});
for(const id of ['berserker','orc','thief','templar','troll','illusionist','phantom','wraith','water','wizard','fire','seer','shifter','vampire','demon','conjurer'])test('Especial '+id+': custo, recarga e estado finito',b=>{const a=training(b,id);a.enemy.x=a.player.x+50;a.enemy.y=a.player.y;const old=a.player.st;assert(b.d.skill(a.player,a.enemy.x,a.enemy.y));assert(a.player.st<old);assert(a.player.skillCd>0);assert.equal(b.d.skill(a.player,a.enemy.x,a.enemy.y),false);for(let i=0;i<60;i++)b.t.updateArena(1/120);assert(Number.isFinite(a.player.hp)&&Number.isFinite(a.player.x)&&Number.isFinite(a.enemy.hp))});
console.log(JSON.stringify({method:'Node VM com DOM simulado; código original carregado sem alteração do arquivo; funções internas expostas somente na memória',passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length,results},null,2));
